In [1]:
# Basic setting for Jupyter_notebook to import utils
import os
import sys

notebook_path = os.path.abspath("")
project_root = os.path.abspath(os.path.join(notebook_path, "../../"))

sys.path.append(project_root)

# 2 ERA5_DATA_PROCESSING

## Data EDA

In [2]:
import os
import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from utils import folder_utils
from tqdm import tqdm

In [3]:
# Example usage

country = "GB"
data_folder = "data"
data_test_category = "test_data"
data_read_category = "raw_data"
data_save_category = "processed_data"
# output_folder = "ASOS_DATA"
output_folder2 ="ERA5_DATA"

In [4]:
folder_utils.create_folder( country, data_folder, data_test_category, output_folder2)

Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/test_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


'/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/test_data/ERA5_DATA/GB_ERA5_DATA'

In [5]:
def extract_data_nc_to_xr(country, data_folder, data_category, output_folder):
    # Specify the folder path
    input_folder_path = folder_utils.find_folder(
        country, data_folder, data_category, output_folder
    )
    raw_ds = None  # Initialize raw_ds outside the loop
    nc_files = [
        f
        for f in os.listdir(input_folder_path)
        if f.endswith('.nc') and "era5_station_network" not in f
    ]
    # Read and merge the csv files in queue
    for nc_file in tqdm(nc_files):
        nc_file_path = os.path.join(input_folder_path, nc_file)
        raw_ds = xr.open_dataset(nc_file_path)
        # raw_df = pd.concat([raw_df, df], ignore_index=True)

    return raw_ds


In [6]:
ds = extract_data_nc_to_xr(country, data_folder, data_test_category, output_folder2)

100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.38it/s]


In [7]:
print(ds)

<xarray.Dataset>
Dimensions:    (longitude: 41, latitude: 45, time: 744)
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2023-01-01 ... 2023-01-31T23:00:00
Data variables:
    u10        (time, latitude, longitude) float32 ...
    v10        (time, latitude, longitude) float32 ...
    d2m        (time, latitude, longitude) float32 ...
    t2m        (time, latitude, longitude) float32 ...
    i10fg      (time, latitude, longitude) float32 ...
    msl        (time, latitude, longitude) float32 ...
    skt        (time, latitude, longitude) float32 ...
    sp         (time, latitude, longitude) float32 ...
    tp         (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-08-14 13:08:35 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...


In [8]:
ds.dims

Frozen({'longitude': 41, 'latitude': 45, 'time': 744})

In [9]:
ds.data_vars

Data variables:
    u10      (time, latitude, longitude) float32 ...
    v10      (time, latitude, longitude) float32 ...
    d2m      (time, latitude, longitude) float32 ...
    t2m      (time, latitude, longitude) float32 ...
    i10fg    (time, latitude, longitude) float32 ...
    msl      (time, latitude, longitude) float32 ...
    skt      (time, latitude, longitude) float32 ...
    sp       (time, latitude, longitude) float32 ...
    tp       (time, latitude, longitude) float32 ...

In [10]:
ds.coords

Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2023-01-01 ... 2023-01-31T23:00:00

In [11]:
ds.attrs

{'Conventions': 'CF-1.6',
 'history': '2023-08-14 13:08:35 GMT by grib_to_netcdf-2.25.1: /opt/ecmwf/mars-client/bin/grib_to_netcdf.bin -S param -o /cache/data9/adaptor.mars.internal-1692018500.2390654-25204-1-38ad28e7-7189-4dcf-abc4-d4ef8d4cf8e3.nc /cache/tmp/38ad28e7-7189-4dcf-abc4-d4ef8d4cf8e3-adaptor.mars.internal-1692018168.885484-25204-1-tmp.grib'}

In [12]:
ds.longitude

<xarray.DataArray 'longitude' (longitude: 41)>
array([-8.  , -7.75, -7.5 , -7.25, -7.  , -6.75, -6.5 , -6.25, -6.  , -5.75,
       -5.5 , -5.25, -5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25,
       -3.  , -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,
        2.  ], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
Attributes:
    units:      degrees_east
    long_name:  longitude

In [13]:
ds.latitude

<xarray.DataArray 'latitude' (latitude: 45)>
array([61.  , 60.75, 60.5 , 60.25, 60.  , 59.75, 59.5 , 59.25, 59.  , 58.75,
       58.5 , 58.25, 58.  , 57.75, 57.5 , 57.25, 57.  , 56.75, 56.5 , 56.25,
       56.  , 55.75, 55.5 , 55.25, 55.  , 54.75, 54.5 , 54.25, 54.  , 53.75,
       53.5 , 53.25, 53.  , 52.75, 52.5 , 52.25, 52.  , 51.75, 51.5 , 51.25,
       51.  , 50.75, 50.5 , 50.25, 50.  ], dtype=float32)
Coordinates:
  * latitude  (latitude) float32 61.0 60.75 60.5 60.25 ... 50.75 50.5 50.25 50.0
Attributes:
    units:      degrees_north
    long_name:  latitude

In [14]:
ds.time

<xarray.DataArray 'time' (time: 744)>
array(['2023-01-01T00:00:00.000000000', '2023-01-01T01:00:00.000000000',
       '2023-01-01T02:00:00.000000000', ..., '2023-01-31T21:00:00.000000000',
       '2023-01-31T22:00:00.000000000', '2023-01-31T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2023-01-01 ... 2023-01-31T23:00:00
Attributes:
    long_name:  time

In [15]:
ds.d2m.attrs

{'units': 'K', 'long_name': '2 metre dewpoint temperature'}

In [16]:
ds.d2m.long_name

'2 metre dewpoint temperature'

In [17]:
ds.longitude.shape

(41,)

In [18]:
ds.latitude.shape[0]

45

In [19]:
ds.latitude.shape

(45,)

In [20]:
ds.latitude.values[0]

61.0

In [21]:
ds.d2m.shape

(744, 45, 41)

In [22]:
print('Latitudes and longitudes of domain corners:')
pt1 = 0
pt2 = 0
print('  0, 0:        ', ds.latitude.values[pt1], ds.longitude.values[pt2])
pt1 = ds.latitude.shape[0] - 1
print('  0, x-max:    ', ds.latitude.values[pt1], ds.longitude.values[pt2])
pt = ds.latitude.shape[0] - 1
print('  y-max, 0:    ', ds.latitude.values[pt], ds.longitude.values[pt])
pt = ds.latitude.shape[0] - 1
pt2 = ds.longitude.shape[0] - 1
print('  y-max, x-max:', ds.latitude.values[pt], ds.longitude.values[pt2])

Latitudes and longitudes of domain corners:
  0, 0:         61.0 -8.0
  0, x-max:     50.0 -8.0


IndexError: index 44 is out of bounds for axis 0 with size 41

In [23]:
ds.latitude.values # 提取数值

array([61.  , 60.75, 60.5 , 60.25, 60.  , 59.75, 59.5 , 59.25, 59.  ,
       58.75, 58.5 , 58.25, 58.  , 57.75, 57.5 , 57.25, 57.  , 56.75,
       56.5 , 56.25, 56.  , 55.75, 55.5 , 55.25, 55.  , 54.75, 54.5 ,
       54.25, 54.  , 53.75, 53.5 , 53.25, 53.  , 52.75, 52.5 , 52.25,
       52.  , 51.75, 51.5 , 51.25, 51.  , 50.75, 50.5 , 50.25, 50.  ],
      dtype=float32)

In [24]:
ds.latitude.values[3:5]   # like numpy

array([60.25, 60.  ], dtype=float32)

In [25]:
# Data Description
for i in ds.data_vars:
    print("--------------------------------------------------------------------")
    print(i)
    print("--------------------------------------------------------------------")
    var_data = ds[i]
    print(var_data)

--------------------------------------------------------------------
u10
--------------------------------------------------------------------
<xarray.DataArray 'u10' (time: 744, latitude: 45, longitude: 41)>
[1372680 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2023-01-01 ... 2023-01-31T23:00:00
Attributes:
    units:      m s**-1
    long_name:  10 metre U wind component
--------------------------------------------------------------------
v10
--------------------------------------------------------------------
<xarray.DataArray 'v10' (time: 744, latitude: 45, longitude: 41)>
[1372680 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) date

In [47]:
# data values
for i in ds.data_vars:
    var_data = ds[i]
    print(var_data.values)

[[[ 5.74171     5.559723    5.412111   ...  1.9058204   1.9516544
    2.0561285 ]
  [ 5.0097165   4.820315    4.5884495  ...  0.73436093  0.7768247
    0.86781836]
  [ 4.177293    3.962952    3.7021034  ... -0.24163055 -0.1870346
   -0.12435007]
  ...
  [ 9.254741    9.186665    9.167117   ...  6.9805727   6.049741
    6.3328323 ]
  [ 9.237216    9.113869    9.058599   ...  6.8619437   6.0146914
    6.0807457 ]
  [ 9.562098    9.437403    9.448187   ...  5.9432445   5.9998627
    6.034238  ]]

 [[ 6.154889    5.8825817   5.610949   ...  1.2587543   1.274257
    1.3173945 ]
  [ 5.3581886   5.0703793   4.719885   ...  0.12301803  0.1533494
    0.1978352 ]
  [ 4.4206166   4.1051717   3.7364788  ... -0.7693939  -0.7094059
   -0.67503023]
  ...
  [10.108059    9.888327    9.628826   ...  8.693951    7.320956
    7.198283  ]
  [10.405306   10.035938    9.724538   ...  8.018575    6.7372484
    6.4844885 ]
  [10.566399   10.195009    9.959774   ...  6.4635935   6.3341804
    6.156911  ]]

 [[

In [38]:
def extract_data_nc_to_xr(country, data_folder, data_category, output_folder):
    # Specify the folder path
    input_folder_path = folder_utils.find_folder(
        country, data_folder, data_category, output_folder
    )
    raw_ds = None  # Initialize raw_ds outside the loop
    nc_files = [
        f
        for f in os.listdir(input_folder_path)
        if f.endswith('.nc') and "era5_station_network" not in f
    ]
    # Read and merge the csv files in queue
    nc_files_path =[]
    for nc_file in tqdm(nc_files):
        nc_file_path = os.path.join(input_folder_path, nc_file)
        nc_files_path.append(nc_file_path)
        # raw_ds = xr.open_dataset(nc_file_path)
        # raw_df = pd.concat([raw_df, df], ignore_index=True)

    return  nc_files_path

In [29]:
# Example usage

country = "GB"
data_folder = "data"
data_test_category = "test_data"
data_read_category = "raw_data"
data_save_category = "processed_data"
# output_folder = "ASOS_DATA"
output_folder2 ="ERA5_DATA

SyntaxError: EOL while scanning string literal (4200837596.py, line 9)

In [39]:
nc_file_path = extract_data_nc_to_xr(country, data_folder, data_test_category, output_folder2)

100%|███████████████████████████████████████████████| 2/2 [00:00<00:00, 9383.23it/s]


In [40]:
nc_file_path

['/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/test_data/ERA5_DATA/GB_ERA5_DATA/era5_pressure_level_2022_02_1000.nc',
 '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/test_data/ERA5_DATA/GB_ERA5_DATA/era5_single_level_2023_01.nc']

In [43]:
ds2 = xr.open_dataset(nc_file_path[0])

In [44]:
# Data Description
for i in ds2.data_vars:
    print("--------------------------------------------------------------------")
    print(i)
    print("--------------------------------------------------------------------")
    var_data = ds2[i]
    print(var_data)

--------------------------------------------------------------------
r
--------------------------------------------------------------------
<xarray.DataArray 'r' (time: 672, latitude: 45, longitude: 41)>
[1239840 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2022-02-01 ... 2022-02-28T23:00:00
Attributes:
    units:          %
    long_name:      Relative humidity
    standard_name:  relative_humidity
--------------------------------------------------------------------
q
--------------------------------------------------------------------
<xarray.DataArray 'q' (time: 672, latitude: 45, longitude: 41)>
[1239840 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  

In [49]:
# data values
for i in ds2.data_vars:
    var_data = ds2[i]
    print('----------------------------------------')
    print(var_data.values)
    print('----------------------------------------')

----------------------------------------
[[[80.47372  82.185234 83.93959  ... 77.920364 77.62262  76.74437 ]
  [80.34091  81.25129  82.48941  ... 80.47372  80.92355  80.56797 ]
  [80.482285 80.58296  81.1656   ... 80.94711  82.22379  83.34624 ]
  ...
  [86.52508  86.43511  86.23161  ... 84.020996 85.107025 84.79    ]
  [85.91887  85.49474  85.077034 ... 79.12635  82.088844 83.26698 ]
  [84.61863  84.014565 83.47048  ... 79.68972  81.8018   81.59616 ]]

 [[78.822174 79.104935 78.920715 ... 81.60902  80.25308  79.818245]
  [79.745415 80.06458  79.70471  ... 80.99424  80.81859  81.429085]
  [81.10777  81.099205 80.67507  ... 78.775055 79.419815 80.67507 ]
  ...
  [88.16591  88.91992  89.2091   ... 84.3573   86.60434  88.05023 ]
  [87.814606 88.14235  88.213036 ... 79.745415 82.57295  85.56543 ]
  [86.78855  86.767136 86.767136 ... 80.72434  82.59223  84.22235 ]]

 [[78.80076  79.02782  79.16063  ... 88.10807  87.61754  85.29981 ]
  [79.60618  79.77754  79.90178  ... 84.17094  86.32372  86

## Data Match

In [2]:
import os
import re
import xarray as xr
from utils import folder_utils
from tqdm import tqdm

In [3]:
# Example usage

country = "GB"
data_folder = "data"
data_test_category = "test_data"
data_read_category = "raw_data"
data_save_category = "processed_data"
# output_folder = "ASOS_DATA"
output_folder2 = "ERA5_DATA"

In [4]:
def extract_year_month_from_filename(filename):
    match = re.search(r"(\d{4})_(\d{2})", filename)
    if match:
        year = int(match.group(1))
        month = int(match.group(2))
        month = f"{month:02}"
        return year, month
    else:
        raise ValueError(f"Cannot extract year and month from filename: {filename}")

In [16]:
def save_era5_processed_data(
    merged_ds, year, month, country, data_folder, data_category, output_folder
):
    output_directory = folder_utils.create_folder(
        country, data_folder, data_category, output_folder
    )
    output_filename = f"{country}_ERA5_{year}_{month}_processed_data.nc"
    output_filepath = os.path.join(output_directory, output_filename)
    merged_ds.to_netcdf(output_filepath)
    print(f"{output_filename} done!")

In [19]:
def extract_merge_nc_data(
    country, data_folder, data_read_category, data_save_category, output_folder
):
    input_folder_path = folder_utils.find_folder(
        country, data_folder, data_read_category, output_folder
    )

    # Get all the single_level data filename
    nc_files_single_level = [
        f
        for f in os.listdir(input_folder_path)
        if f.endswith(".nc") and "single_level" in f
    ]

    # Create a new blank dataset to store the merged data
    # merged_ds = xr.Dataset()

    # Loop single_level files
    for nc_file_A in tqdm(nc_files_single_level):
        nc_file_path_A = os.path.join(input_folder_path, nc_file_A)

        #
        ds_A = xr.open_dataset(nc_file_path_A)

        # extract the corresponding year and month
        year_A, month_A = extract_year_month_from_filename(nc_file_A)

        # Build the pressure level file path
        nc_file_B = f"era5_pressure_level_{year_A}_{month_A}_1000.nc"
        nc_file_path_B = os.path.join(input_folder_path, nc_file_B)

        #
        ds_B = xr.open_dataset(nc_file_path_B)

        # Merge single_level and pressure level by the key "time" and overwrite ds_A
        ds_A = ds_A.combine_first(ds_B)

        # Close all dataset
        ds_A.close()
        ds_B.close()

        save_era5_processed_data(
            ds_A, year_A, month_A,country, data_folder, data_save_category, output_folder
        )


In [20]:
extract_merge_nc_data(
    country, data_folder, data_read_category, data_save_category, output_folder2
)


  0%|                                                        | 0/20 [00:00<?, ?it/s]

Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


  5%|██▍                                             | 1/20 [00:01<00:19,  1.03s/it]

GB_ERA5_2023_06_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 10%|████▊                                           | 2/20 [00:01<00:13,  1.29it/s]

GB_ERA5_2022_08_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 15%|███████▏                                        | 3/20 [00:02<00:11,  1.52it/s]

GB_ERA5_2023_02_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 20%|█████████▌                                      | 4/20 [00:02<00:09,  1.71it/s]

GB_ERA5_2023_03_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 25%|████████████                                    | 5/20 [00:03<00:07,  1.88it/s]

GB_ERA5_2023_07_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 30%|██████████████▍                                 | 6/20 [00:03<00:06,  2.02it/s]

GB_ERA5_2022_09_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 35%|████████████████▊                               | 7/20 [00:03<00:05,  2.25it/s]

GB_ERA5_2022_12_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 40%|███████████████████▏                            | 8/20 [00:04<00:05,  2.37it/s]

GB_ERA5_2022_02_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 50%|███████████████████████▌                       | 10/20 [00:04<00:03,  3.04it/s]

GB_ERA5_2022_06_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.
GB_ERA5_2023_08_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 55%|█████████████████████████▊                     | 11/20 [00:05<00:03,  2.97it/s]

GB_ERA5_2022_07_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 60%|████████████████████████████▏                  | 12/20 [00:05<00:02,  2.94it/s]

GB_ERA5_2022_03_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 65%|██████████████████████████████▌                | 13/20 [00:05<00:02,  2.99it/s]

GB_ERA5_2022_04_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 70%|████████████████████████████████▉              | 14/20 [00:06<00:02,  2.66it/s]

GB_ERA5_2022_10_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 75%|███████████████████████████████████▎           | 15/20 [00:06<00:01,  2.55it/s]

GB_ERA5_2022_11_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 80%|█████████████████████████████████████▌         | 16/20 [00:07<00:01,  2.24it/s]

GB_ERA5_2022_01_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


 85%|███████████████████████████████████████▉       | 17/20 [00:07<00:01,  2.19it/s]

GB_ERA5_2022_05_processed_data.nc done!


 90%|██████████████████████████████████████████▎    | 18/20 [00:08<00:00,  2.30it/s]

Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.
GB_ERA5_2023_04_processed_data.nc done!


 95%|████████████████████████████████████████████▋  | 19/20 [00:08<00:00,  2.44it/s]

Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.
GB_ERA5_2023_05_processed_data.nc done!
Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/processed_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


100%|███████████████████████████████████████████████| 20/20 [00:08<00:00,  2.23it/s]

GB_ERA5_2023_01_processed_data.nc done!


In [7]:
print("1")

1


In [21]:
input_folder_path = folder_utils.find_folder(
    country, data_folder, data_read_category, output_folder2
)

In [22]:
input_folder_path 

'/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/raw_data/ERA5_DATA/GB_ERA5_DATA'