In [ ]:
# Name: Wenqi Wang
# Github username: acse-ww721

In [1]:
# Basic setting for Jupyter_notebook to import utils
import os
import sys

notebook_path = os.path.abspath("")
project_root = os.path.abspath(os.path.join(notebook_path, "../../"))

sys.path.append(project_root)

In [2]:
"""V2"""

'V2'

# 2 ERA5_DATA_PROCESSING

## Data EDA

In [4]:
import os
import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
# import cartopy.crs as ccrs
from utils import folder_utils
from tqdm import tqdm

In [5]:
# Example usage

country = "GB"
data_folder = "data"
data_test_category = "test_data"
data_read_category = "raw_data"
data_save_category = "processed_data"
# output_folder = "ASOS_DATA"
output_folder2 ="ERA5_DATA"

In [6]:
folder_utils.create_folder( country, data_folder, data_test_category, output_folder2)

Folder 'F:\JuPyterNotebook\irp_ww721_bakcup\data\test_data\ERA5_DATA\GB_ERA5_DATA' created successfully.


'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\test_data\\ERA5_DATA\\GB_ERA5_DATA'

In [7]:
def extract_data_nc_to_xr(country, data_folder, data_category, output_folder):
    # Specify the folder path
    input_folder_path = folder_utils.find_folder(
        country, data_folder, data_category, output_folder
    )
    raw_ds = None  # Initialize raw_ds outside the loop
    nc_files = [
        f
        for f in os.listdir(input_folder_path)
        if f.endswith('.nc') and "era5_station_network" not in f
    ]
    # Read and merge the csv files in queue
    for nc_file in tqdm(nc_files):
        nc_file_path = os.path.join(input_folder_path, nc_file)
        raw_ds = xr.open_dataset(nc_file_path)
        # raw_df = pd.concat([raw_df, df], ignore_index=True)

    return raw_ds


In [ ]:
ds = extract_data_nc_to_xr(country, data_folder, data_test_category, output_folder2)

In [7]:
print(ds)

<xarray.Dataset>
Dimensions:    (longitude: 37, latitude: 33, time: 720)
Coordinates:
  * longitude  (longitude) float32 -7.0 -6.75 -6.5 -6.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 58.0 57.75 57.5 57.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2008-11-01 ... 2008-11-30T23:00:00
Data variables:
    t          (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-08-26 21:23:07 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...


In [8]:
ds.dims

Frozen({'longitude': 37, 'latitude': 33, 'time': 720})

In [9]:
ds.data_vars

Data variables:
    t        (time, latitude, longitude) float32 ...

In [10]:
ds.coords

Coordinates:
  * longitude  (longitude) float32 -7.0 -6.75 -6.5 -6.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 58.0 57.75 57.5 57.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2008-11-01 ... 2008-11-30T23:00:00

In [11]:
ds.attrs

{'Conventions': 'CF-1.6',
 'history': '2023-08-26 21:23:07 GMT by grib_to_netcdf-2.25.1: /opt/ecmwf/mars-client/bin/grib_to_netcdf.bin -S param -o /cache/data9/adaptor.mars.internal-1693084986.468713-31194-10-5f7e33e6-dc9a-468e-bbb4-df30f1d52c8b.nc /cache/tmp/5f7e33e6-dc9a-468e-bbb4-df30f1d52c8b-adaptor.mars.internal-1693084950.2077148-31194-19-tmp.grib'}

In [12]:
ds.longitude

<xarray.DataArray 'longitude' (longitude: 37)>
array([-7.  , -6.75, -6.5 , -6.25, -6.  , -5.75, -5.5 , -5.25, -5.  , -4.75,
       -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25, -3.  , -2.75, -2.5 , -2.25,
       -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,
        0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 -7.0 -6.75 -6.5 -6.25 ... 1.25 1.5 1.75 2.0
Attributes:
    units:      degrees_east
    long_name:  longitude

In [13]:
ds.latitude

<xarray.DataArray 'latitude' (latitude: 33)>
array([58.  , 57.75, 57.5 , 57.25, 57.  , 56.75, 56.5 , 56.25, 56.  , 55.75,
       55.5 , 55.25, 55.  , 54.75, 54.5 , 54.25, 54.  , 53.75, 53.5 , 53.25,
       53.  , 52.75, 52.5 , 52.25, 52.  , 51.75, 51.5 , 51.25, 51.  , 50.75,
       50.5 , 50.25, 50.  ], dtype=float32)
Coordinates:
  * latitude  (latitude) float32 58.0 57.75 57.5 57.25 ... 50.75 50.5 50.25 50.0
Attributes:
    units:      degrees_north
    long_name:  latitude

In [14]:
ds.time

<xarray.DataArray 'time' (time: 720)>
array(['2008-11-01T00:00:00.000000000', '2008-11-01T01:00:00.000000000',
       '2008-11-01T02:00:00.000000000', ..., '2008-11-30T21:00:00.000000000',
       '2008-11-30T22:00:00.000000000', '2008-11-30T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2008-11-01 ... 2008-11-30T23:00:00
Attributes:
    long_name:  time

In [15]:
ds.t.attrs

{'units': 'K', 'long_name': 'Temperature', 'standard_name': 'air_temperature'}

In [16]:
ds.d2m.long_name

'2 metre dewpoint temperature'

In [16]:
ds.longitude.shape

(37,)

In [17]:
ds.latitude.shape[0]

33

In [18]:
ds.latitude.shape

(33,)

In [19]:
ds.latitude.values[0]

58.0

In [20]:
ds.t.shape

(720, 33, 37)

In [22]:
print('Latitudes and longitudes of domain corners:')
pt1 = 0
pt2 = 0
print('  0, 0:        ', ds.latitude.values[pt1], ds.longitude.values[pt2])
pt1 = ds.latitude.shape[0] - 1
print('  0, x-max:    ', ds.latitude.values[pt1], ds.longitude.values[pt2])
pt = ds.latitude.shape[0] - 1
print('  y-max, 0:    ', ds.latitude.values[pt], ds.longitude.values[pt])
pt = ds.latitude.shape[0] - 1
pt2 = ds.longitude.shape[0] - 1
print('  y-max, x-max:', ds.latitude.values[pt], ds.longitude.values[pt2])

Latitudes and longitudes of domain corners:
  0, 0:         61.0 -8.0
  0, x-max:     50.0 -8.0


IndexError: index 44 is out of bounds for axis 0 with size 41

In [23]:
ds.latitude.values # 提取数值

array([61.  , 60.75, 60.5 , 60.25, 60.  , 59.75, 59.5 , 59.25, 59.  ,
       58.75, 58.5 , 58.25, 58.  , 57.75, 57.5 , 57.25, 57.  , 56.75,
       56.5 , 56.25, 56.  , 55.75, 55.5 , 55.25, 55.  , 54.75, 54.5 ,
       54.25, 54.  , 53.75, 53.5 , 53.25, 53.  , 52.75, 52.5 , 52.25,
       52.  , 51.75, 51.5 , 51.25, 51.  , 50.75, 50.5 , 50.25, 50.  ],
      dtype=float32)

In [24]:
ds.latitude.values[3:5]   # like numpy

array([60.25, 60.  ], dtype=float32)

In [21]:
# Data Description
for i in ds.data_vars:
    print("--------------------------------------------------------------------")
    print(i)
    print("--------------------------------------------------------------------")
    var_data = ds[i]
    print(var_data)

--------------------------------------------------------------------
t
--------------------------------------------------------------------
<xarray.DataArray 't' (time: 720, latitude: 33, longitude: 37)>
[879120 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -7.0 -6.75 -6.5 -6.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 58.0 57.75 57.5 57.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2008-11-01 ... 2008-11-30T23:00:00
Attributes:
    units:          K
    long_name:      Temperature
    standard_name:  air_temperature


In [22]:
# data values
for i in ds.data_vars:
    var_data = ds[i]
    print(var_data.values)

[[[268.44385 268.27588 268.15677 ... 268.02    268.09814 268.28564]
  [268.2913  268.22104 268.1331  ... 267.88507 267.9809  268.25034]
  [268.19962 268.1782  268.11957 ... 268.1917  268.32474 268.59793]
  ...
  [270.3265  270.25433 270.17017 ... 272.31662 272.68976 273.00616]
  [270.45538 270.35956 270.28552 ... 272.85208 273.20944 273.49054]
  [270.5591  270.50424 270.4986  ... 273.31693 273.5706  273.73477]]

 [[268.8606  268.6201  268.44836 ... 268.0929  268.0478  268.06546]
  [268.58102 268.45026 268.33902 ... 267.88583 267.8644  267.9347 ]
  [268.3702  268.3097  268.2432  ... 267.9873  268.03052 268.15152]
  ...
  [270.4073  270.34866 270.263   ... 272.7044  273.0753  273.34888]
  [270.4971  270.42496 270.36633 ... 273.2493  273.5187  273.71185]
  [270.5869  270.5422  270.54407 ... 273.73743 273.84113 273.89185]]

 [[269.13452 268.86472 268.67157 ... 268.21463 268.0835  267.98016]
  [268.7828  268.6325  268.51715 ... 268.02298 267.88058 267.78476]
  [268.4664  268.4138  268.3687 

In [28]:
ddeg_out_lat = 0.25
lat_list = np.arange(50, 58, ddeg_out_lat)
print(lat_list)
print(len(lat_list))

[50.   50.25 50.5  50.75 51.   51.25 51.5  51.75 52.   52.25 52.5  52.75
 53.   53.25 53.5  53.75 54.   54.25 54.5  54.75 55.   55.25 55.5  55.75
 56.   56.25 56.5  56.75 57.   57.25 57.5  57.75]
32


In [35]:
ddeg_out_lon = 0.125
lon_list = np.arange(-6,2 , ddeg_out_lon)
print(lon_list)
print(len(lon_list))

[-6.    -5.875 -5.75  -5.625 -5.5   -5.375 -5.25  -5.125 -5.    -4.875
 -4.75  -4.625 -4.5   -4.375 -4.25  -4.125 -4.    -3.875 -3.75  -3.625
 -3.5   -3.375 -3.25  -3.125 -3.    -2.875 -2.75  -2.625 -2.5   -2.375
 -2.25  -2.125 -2.    -1.875 -1.75  -1.625 -1.5   -1.375 -1.25  -1.125
 -1.    -0.875 -0.75  -0.625 -0.5   -0.375 -0.25  -0.125  0.     0.125
  0.25   0.375  0.5    0.625  0.75   0.875  1.     1.125  1.25   1.375
  1.5    1.625  1.75   1.875]
64


In [38]:
def extract_data_nc_to_xr(country, data_folder, data_category, output_folder):
    # Specify the folder path
    input_folder_path = folder_utils.find_folder(
        country, data_folder, data_category, output_folder
    )
    raw_ds = None  # Initialize raw_ds outside the loop
    nc_files = [
        f
        for f in os.listdir(input_folder_path)
        if f.endswith('.nc') and "era5_station_network" not in f
    ]
    # Read and merge the csv files in queue
    nc_files_path =[]
    for nc_file in tqdm(nc_files):
        nc_file_path = os.path.join(input_folder_path, nc_file)
        nc_files_path.append(nc_file_path)
        # raw_ds = xr.open_dataset(nc_file_path)
        # raw_df = pd.concat([raw_df, df], ignore_index=True)

    return  nc_files_path

In [29]:
# Example usage

country = "GB"
data_folder = "data"
data_test_category = "test_data"
data_read_category = "raw_data"
data_save_category = "processed_data"
# output_folder = "ASOS_DATA"
output_folder2 ="ERA5_DATA

SyntaxError: EOL while scanning string literal (4200837596.py, line 9)

In [39]:
nc_file_path = extract_data_nc_to_xr(country, data_folder, data_test_category, output_folder2)

100%|███████████████████████████████████████████████| 2/2 [00:00<00:00, 9383.23it/s]


In [40]:
nc_file_path

['/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/test_data/ERA5_DATA/GB_ERA5_DATA/era5_pressure_level_2022_02_1000.nc',
 '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/test_data/ERA5_DATA/GB_ERA5_DATA/era5_single_level_2023_01.nc']

In [43]:
ds2 = xr.open_dataset(nc_file_path[0])

In [44]:
# Data Description
for i in ds2.data_vars:
    print("--------------------------------------------------------------------")
    print(i)
    print("--------------------------------------------------------------------")
    var_data = ds2[i]
    print(var_data)

--------------------------------------------------------------------
r
--------------------------------------------------------------------
<xarray.DataArray 'r' (time: 672, latitude: 45, longitude: 41)>
[1239840 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2022-02-01 ... 2022-02-28T23:00:00
Attributes:
    units:          %
    long_name:      Relative humidity
    standard_name:  relative_humidity
--------------------------------------------------------------------
q
--------------------------------------------------------------------
<xarray.DataArray 'q' (time: 672, latitude: 45, longitude: 41)>
[1239840 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  

In [49]:
# data values
for i in ds2.data_vars:
    var_data = ds2[i]
    print('----------------------------------------')
    print(var_data.values)
    print('----------------------------------------')

----------------------------------------
[[[80.47372  82.185234 83.93959  ... 77.920364 77.62262  76.74437 ]
  [80.34091  81.25129  82.48941  ... 80.47372  80.92355  80.56797 ]
  [80.482285 80.58296  81.1656   ... 80.94711  82.22379  83.34624 ]
  ...
  [86.52508  86.43511  86.23161  ... 84.020996 85.107025 84.79    ]
  [85.91887  85.49474  85.077034 ... 79.12635  82.088844 83.26698 ]
  [84.61863  84.014565 83.47048  ... 79.68972  81.8018   81.59616 ]]

 [[78.822174 79.104935 78.920715 ... 81.60902  80.25308  79.818245]
  [79.745415 80.06458  79.70471  ... 80.99424  80.81859  81.429085]
  [81.10777  81.099205 80.67507  ... 78.775055 79.419815 80.67507 ]
  ...
  [88.16591  88.91992  89.2091   ... 84.3573   86.60434  88.05023 ]
  [87.814606 88.14235  88.213036 ... 79.745415 82.57295  85.56543 ]
  [86.78855  86.767136 86.767136 ... 80.72434  82.59223  84.22235 ]]

 [[78.80076  79.02782  79.16063  ... 88.10807  87.61754  85.29981 ]
  [79.60618  79.77754  79.90178  ... 84.17094  86.32372  86

## Data Merge and regrid

### All used function

In [2]:
%env ESMFMKFILE


'D:\\anaconda3\\envs\\da\\Library\\lib\\esmf.mk'

In [3]:
import os
esmfmkfile = os.environ.get("ESMFMKFILE")
print("ESMFMKFILE path:", esmfmkfile)


ESMFMKFILE path: D:\anaconda3\envs\da\Library\lib\esmf.mk


In [4]:
# Basic setting for Jupyter_notebook to import utils
import os
import sys

notebook_path = os.path.abspath("")
project_root = os.path.abspath(os.path.join(notebook_path, "../../"))

sys.path.append(project_root)

In [5]:

def get_current_directory():
    if "__file__" in globals():
        # Running in a Python file
        return os.path.abspath(os.path.dirname(__file__))
    else:
        # Running in a Jupyter Notebook
        return os.path.abspath(os.path.dirname(""))


def find_folder(c, data_folder, data_category, output_folder):
    # c: country list
    current_directory = get_current_directory()
    project_root = os.path.abspath(os.path.join(current_directory, "..", ".."))
    folder_name = f"{c}_{output_folder}"
    folder_path = os.path.join(
        project_root, data_folder, data_category, output_folder, folder_name
    )

    return folder_path


def create_folder(c, data_folder, data_category, output_folder):
    # c: country list
    folder_path = find_folder(c, data_folder, data_category, output_folder)

    try:
        os.makedirs(folder_path, exist_ok=True)
        print(f"Folder '{folder_path}' created successfully.")
    except FileExistsError:
        print(f"Folder '{folder_path}' already exists.")

    return folder_path


In [6]:
import os
import re
import xarray as xr
import numpy as np
import xesmf as xe
import dask
from tqdm import tqdm

In [7]:
PREFIX = "era5_pressure_level_"
SUFFIX = "_850.nc"

In [8]:
def get_era5_list_0(country, data_folder, data_category, output_folder):
    input_folder_path = find_folder(
        country, data_folder, data_category, output_folder
    )
    nc_files = [
        f for f in os.listdir(input_folder_path) if f.endswith(".nc") and "era5"  in f
    ]
    return [
        os.path.join(input_folder_path, nc_file) for nc_file in nc_files
    ]  # list for era5 nc files path

In [9]:
def get_era5_list(country, data_folder, data_category, output_folder):
    input_folder_path = find_folder(
        country, data_folder, data_category, output_folder
    )
    nc_files = [
        f for f in os.listdir(input_folder_path) if f.endswith(".nc") and "regrid"  not in f
    ]
    return [
        os.path.join(input_folder_path, nc_file) for nc_file in nc_files
    ]  # list for era5 nc files path

In [10]:
def merge_ds_by_year(era5_list, country, data_folder, data_category, output_folder):
    """
    Merge netcdf files by year in the given list.
    """

    # Organize files by year
    files_by_year = {}
    pattern = r"era5_pressure_level_(\d{4})_\d{2}_\d{3}\.nc"


    for file in era5_list:
        match = re.search(pattern, file)
        if match:
            year = match.group(1)
            if year not in files_by_year:
                files_by_year[year] = []
            files_by_year[year].append(file)

    # Merge and save for each year
    # Calculate the output folder outside the loop
    output_folder_path = find_folder(
        country, data_folder, data_category, output_folder
    )
    
    for year, file_list in files_by_year.items():
        merged_ds = xr.open_mfdataset(file_list, combine="by_coords")
        output_filename = os.path.join(output_folder_path, f"{PREFIX}{year}{SUFFIX}")
        merged_ds.to_netcdf(output_filename)
        print(f"Merged data for {year} saved as {output_filename}")

    # Get unique years
    unique_years = list(files_by_year.keys())
    return unique_years

In [11]:
def cutoff_ds(era5_nc_path, lat_min, lat_max, lon_min, lon_max):
    """
    Cut off the dataset with given lat and lon range
    :param ds: Input xarray dataset
    :param lat_min: Minimum latitude
    :param lat_max: Maximum latitude
    :param lon_min: Minimum longitude
    :param lon_max: Maximum longitude
    :return: ds: Cut off dataset
    """
    with xr.open_dataset(era5_nc_path) as ds:
        return ds.sel(
            latitude=slice(lat_max, lat_min),  # Reversed latitudes
            longitude=slice(lon_min, lon_max),
        )


In [12]:
def regrid(ds_in, ddeg_out_lat, ddeg_out_lon, method="bilinear", reuse_weights=True):
    """
    Regrid horizontally (longitude direction).
    :param ds_in: Input xarray dataset
    :param ddeg_out: Output resolution
    :param method: Regridding method
    :param reuse_weights: Reuse weights for regridding
    :return: ds_out: Regridded dataset
    """
    # Rename to ESMF compatible coordinates
    if "latitude" in ds_in.coords:
        ds_in = ds_in.rename({"latitude": "lat", "longitude": "lon"})

    # Create output grid
    grid_out = xr.Dataset(
        {
            "lat": (["lat"], np.arange(50, 58, ddeg_out_lat)),  # 50 - 57.75
            "lon": (["lon"], np.arange(-6, 2.0, ddeg_out_lon)),  # -6 - 1.875
        }
    )

    # Create regridder
    regridder = xe.Regridder(
        ds_in,
        grid_out,
        method,
        periodic=False,  # For a specific region, set periodic to False
        reuse_weights=False, # recalculat weight automatically
    )

    # Hack to speed up regridding of large files
    ds_list = []
    chunk_size = 500
    n_chunks = len(ds_in.time) // chunk_size + 1
    for i in range(n_chunks):
        ds_small = ds_in.isel(time=slice(i * chunk_size, (i + 1) * chunk_size))
        ds_list.append(regridder(ds_small).astype("float32"))
    ds_out = xr.concat(ds_list, dim="time")

    # Set attributes since they get lost during regridding
    for var in ds_out:
        ds_out[var].attrs = ds_in[var].attrs
    ds_out.attrs.update(ds_in.attrs)

    # Regrid dataset
    # ds_out = regridder(ds_in)
    return ds_out

In [13]:
def save_regridded_era5(
    ds_out, year, country, data_folder, data_category, output_folder
):
    prefix = "era5_pressure_level_"
    suffix = "_850.nc"
    output_folder = find_folder(
        country, data_folder, data_category, output_folder
    )
    output_filename = os.path.join(output_folder, f"{prefix}{year}_regrid_filter{suffix}")
    ds_out.to_netcdf(output_filename)
    print(f"Regridded data for {year} saved as {output_filename}")

### Test example

In [14]:
# Example usage

country = "GB"
data_folder = "data"
data_test_category = "test_data"
data_read_category = "raw_data"
data_save_category = "processed_data"
output_folder = "ERA5_DATA"
ddeg_out_lat = 0.25
ddeg_out_lon = 0.125

In [15]:
era5_list = get_era5_list(country, data_folder, data_test_category, output_folder)

In [18]:
era5_list

['F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\test_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_01_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\test_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_02_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\test_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_03_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\test_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_04_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\test_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_05_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\test_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_06_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\test_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_07_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\test_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_08_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\

In [16]:
year_list =[]

In [19]:
year_list = merge_ds_by_year(
    era5_list, country, data_folder, data_save_category, output_folder
)

Merged data for 1979 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1979_850.nc
Merged data for 1980 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1980_850.nc


In [24]:
merge_era5_list = get_era5_list(country, data_folder, data_save_category, output_folder)

In [25]:
merge_era5_list

['F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1980_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1981_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1982_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1983_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1984_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1985_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1986_850.nc',
 'F:\\JuPyterNotebook\\i

In [21]:
ds2 = xr.open_dataset(merge_era5_list[0])
print(ds2)

<xarray.Dataset>
Dimensions:    (time: 8760, latitude: 33, longitude: 37)
Coordinates:
  * time       (time) datetime64[ns] 1979-01-01 ... 1979-12-31T23:00:00
  * longitude  (longitude) float32 -7.0 -6.75 -6.5 -6.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 58.0 57.75 57.5 57.25 ... 50.5 50.25 50.0
Data variables:
    t          (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-08-26 11:48:45 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...


In [25]:
ds3 =  cutoff_ds(merge_era5_list[0], 50, 58, -6, 2)
print(ds3)

<xarray.Dataset>
Dimensions:    (time: 8760, latitude: 33, longitude: 33)
Coordinates:
  * time       (time) datetime64[ns] 1979-01-01 ... 1979-12-31T23:00:00
  * longitude  (longitude) float32 -6.0 -5.75 -5.5 -5.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 58.0 57.75 57.5 57.25 ... 50.5 50.25 50.0
Data variables:
    t          (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-08-26 11:48:45 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...


In [28]:
for merged_ds_path, year in tqdm(zip(merge_era5_list, year_list)):
    ds = xr.open_dataset(merged_ds_path)
    ds = cutoff_ds(merged_ds_path, 50, 58, -6, 2)
    ds_out = regrid(ds, ddeg_out_lat, ddeg_out_lon)
    save_regridded_era5(
        ds_out, year, country, data_folder, data_save_category, output_folder
    )

1it [00:02,  2.36s/it]

Regridded data for 1979 saved as F:\JuPyterNotebook\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1979_regrid_850.nc


2it [00:03,  1.66s/it]

Regridded data for 1980 saved as F:\JuPyterNotebook\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1980_regrid_850.nc


In [32]:
ds4 = xr.open_dataset(merge_era5_list[1])
print(ds4)

<xarray.Dataset>
Dimensions:  (time: 8760, lat: 32, lon: 64)
Coordinates:
  * time     (time) datetime64[ns] 1979-01-01 ... 1979-12-31T23:00:00
  * lon      (lon) float64 -6.0 -5.875 -5.75 -5.625 ... 1.5 1.625 1.75 1.875
  * lat      (lat) float64 50.0 50.25 50.5 50.75 51.0 ... 57.0 57.25 57.5 57.75
Data variables:
    t        (time, lat, lon) float32 ...
Attributes:
    regrid_method:  bilinear
    Conventions:    CF-1.6
    history:        2023-08-26 11:48:45 GMT by grib_to_netcdf-2.25.1: /opt/ec...


### The whole process

In [20]:
# Example usage

country = "GB"
data_folder = "data"
data_test_category = "test_data"
data_read_category = "raw_data"
data_save_category = "processed_data"
output_folder = "ERA5_DATA"
ddeg_out_lat = 0.25
ddeg_out_lon = 0.125

In [21]:
era5_list = get_era5_list_0(country, data_folder, data_read_category, output_folder)

In [22]:
input_folder_path = find_folder(
    country, data_folder, data_read_category, output_folder
)

In [23]:
input_folder_path

'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\raw_data\\ERA5_DATA\\GB_ERA5_DATA'

In [24]:
'F:\\JuPyterNotebook\\irp_ww721_bakcup\\src\\data\\raw_data\\ERA5_DATA\\GB_ERA5_DATA'

'F:\\JuPyterNotebook\\irp_ww721_bakcup\\src\\data\\raw_data\\ERA5_DATA\\GB_ERA5_DATA'

In [25]:
'F:\JuPyterNotebook\irp_ww721_bakcup\data\raw_data\ERA5_DATA\GB_ERA5_DATA'

'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\raw_data\\ERA5_DATA\\GB_ERA5_DATA'

In [26]:
len(era5_list)

528

In [27]:
year_list =[]

In [28]:
year_list = merge_ds_by_year(
    era5_list, country, data_folder, data_save_category, output_folder
)

Merged data for 1979 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1979_850.nc
Merged data for 1980 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1980_850.nc
Merged data for 1981 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1981_850.nc
Merged data for 1982 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1982_850.nc
Merged data for 1983 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1983_850.nc
Merged data for 1984 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1984_850.nc
Merged data for 1985 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1985_850.nc
Merged data f

In [29]:
len(year_list)

44

In [30]:
merge_era5_list = get_era5_list(country, data_folder, data_save_category, output_folder)

In [31]:
merge_era5_list

['F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1979_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1980_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1981_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1982_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1983_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1984_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1985_850.nc',
 'F:\\JuPyterNotebook\\irp_ww721_bakcup\\data\\processed_data\\ERA5_DATA\\GB_ERA5_DATA\\era5_pressure_level_1986_850.nc',
 'F:\\JuPyterNotebook\\i

In [37]:
def fill_nan_new(Z):
    for t in tqdm(range(Z.shape[0])):
        for i in range(Z.shape[1]):

            # Process the start nan of the array
            start = 0
            while start < Z.shape[2] and np.isnan(Z[t, i, start]):
                start += 1
            for j in range(start):
                Z[t, i, j] = Z[t, i, start] if start < Z.shape[2] else np.nan

            # Process the end nan of the array
            end = Z.shape[2] - 1
            while end >= 0 and np.isnan(Z[t, i, end]):
                end -= 1
            for j in range(end + 1, Z.shape[2]):
                Z[t, i, j] = Z[t, i, end] if end >= 0 else np.nan

            # Process the middle nan of the array
            for j in range(1, Z.shape[2] - 1):  # avoid the start and end
                if np.isnan(Z[t, i, j]):
                    prev_val = Z[t, i, j - 1]
                    next_val = Z[t, i, j + 1]

                    # only fill if both values are not nan
                    if not np.isnan(prev_val) and not np.isnan(next_val):
                        Z[t, i, j] = (prev_val + next_val) / 2
                    # if previous value is not nan, use previous value to fill
                    elif not np.isnan(prev_val):
                        Z[t, i, j] = prev_val
                    # if next value is not nan, use next value to fill
                    elif not np.isnan(next_val):
                        Z[t, i, j] = next_val
            Z[t, i, -1] = Z[t, i, -2]
    return Z

In [32]:
def fill_nan(Z):
    for t in tqdm(range(Z.shape[0])):
        for i in range(Z.shape[1]):
            for j in range(1, Z.shape[2] - 1):  # 避免越界，从1开始，到-2结束
                if np.isnan(Z[t, i, j]):
                    prev_val = Z[t, i, j - 1]
                    next_val = Z[t, i, j + 1]

                    # 只有前后都不是nan才进行填充
                    if not np.isnan(prev_val) and not np.isnan(next_val):
                        Z[t, i, j] = (prev_val + next_val) / 2
                    # 如果前一个值不是nan，则使用前一个值填充
                    elif not np.isnan(prev_val):
                        Z[t, i, j] = prev_val
                    # 如果后一个值不是nan，则使用后一个值填充
                    elif not np.isnan(next_val):
                        Z[t, i, j] = next_val
            Z[t, i, -1] = Z[t, i, -2]
    return Z

In [51]:
for merged_ds_path, year in tqdm(zip(merge_era5_list, year_list)):
    # ds = xr.open_dataset(merged_ds_path)
    ds = cutoff_ds(merged_ds_path, 50, 58, -6, 2)
    ds_out = regrid(ds, ddeg_out_lat, ddeg_out_lon)
    ds_out = ds_out.where((ds_out != 0) & ~np.isnan(ds_out), drop=True)
    ds_array = np.asarray(ds_out['t'])
    filled_array=fill_nan_new(ds_array)
    ds_out['t'] = xr.DataArray(filled_array, dims=ds_out['t'].dims, coords=ds_out['t'].coords)

    save_regridded_era5(
        ds_out, year, country, data_folder, data_save_category, output_folder
    )
    ds.close()

0it [00:00, ?it/s]
100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:11<00:00, 778.99it/s]
1it [00:11, 11.93s/it]

Regridded data for 1979 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1979_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:10<00:00, 829.87it/s]
2it [00:23, 11.56s/it]

Regridded data for 1980 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1980_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 817.96it/s]
3it [00:34, 11.46s/it]

Regridded data for 1981 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1981_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 817.94it/s]
4it [00:45, 11.42s/it]

Regridded data for 1982 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1982_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 834.53it/s]
5it [00:57, 11.33s/it]

Regridded data for 1983 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1983_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:10<00:00, 802.16it/s]
6it [01:08, 11.45s/it]

Regridded data for 1984 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1984_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 840.75it/s]
7it [01:19, 11.35s/it]

Regridded data for 1985 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1985_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 820.17it/s]
8it [01:31, 11.37s/it]

Regridded data for 1986 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1986_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 828.44it/s]
9it [01:42, 11.33s/it]

Regridded data for 1987 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1987_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:10<00:00, 840.47it/s]
10it [01:53, 11.27s/it]

Regridded data for 1988 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1988_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 817.38it/s]
11it [02:05, 11.30s/it]

Regridded data for 1989 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1989_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 821.53it/s]
12it [02:16, 11.33s/it]

Regridded data for 1990 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1990_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 844.13it/s]
13it [02:27, 11.24s/it]

Regridded data for 1991 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1991_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:10<00:00, 853.69it/s]
14it [02:38, 11.16s/it]

Regridded data for 1992 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1992_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 834.65it/s]
15it [02:49, 11.16s/it]

Regridded data for 1993 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1993_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 838.66it/s]
16it [03:00, 11.17s/it]

Regridded data for 1994 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1994_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 824.04it/s]
17it [03:12, 11.20s/it]

Regridded data for 1995 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1995_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:10<00:00, 845.96it/s]
18it [03:23, 11.16s/it]

Regridded data for 1996 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1996_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 854.75it/s]
19it [03:34, 11.09s/it]

Regridded data for 1997 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1997_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 824.36it/s]
20it [03:45, 11.15s/it]

Regridded data for 1998 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1998_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 842.90it/s]
21it [03:56, 11.13s/it]

Regridded data for 1999 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_1999_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:10<00:00, 834.81it/s]
22it [04:07, 11.15s/it]

Regridded data for 2000 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2000_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 829.11it/s]
23it [04:18, 11.18s/it]

Regridded data for 2001 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2001_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:09<00:00, 887.59it/s]
24it [04:29, 11.00s/it]

Regridded data for 2002 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2002_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:09<00:00, 905.85it/s]
25it [04:39, 10.79s/it]

Regridded data for 2003 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2003_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:10<00:00, 858.59it/s]
26it [04:50, 10.82s/it]

Regridded data for 2004 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2004_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:11<00:00, 768.35it/s]
27it [05:02, 11.22s/it]

Regridded data for 2005 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2005_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 813.22it/s]
28it [05:14, 11.33s/it]

Regridded data for 2006 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2006_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:09<00:00, 886.14it/s]
29it [05:25, 11.10s/it]

Regridded data for 2007 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2007_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:09<00:00, 910.04it/s]
30it [05:35, 10.85s/it]

Regridded data for 2008 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2008_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 851.70it/s]
31it [05:46, 10.87s/it]

Regridded data for 2009 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2009_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:12<00:00, 694.59it/s]
32it [05:59, 11.58s/it]

Regridded data for 2010 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2010_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:12<00:00, 713.85it/s]
33it [06:12, 11.99s/it]

Regridded data for 2011 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2011_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:12<00:00, 728.04it/s]
34it [06:25, 12.24s/it]

Regridded data for 2012 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2012_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 830.94it/s]
35it [06:36, 11.94s/it]

Regridded data for 2013 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2013_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 854.54it/s]
36it [06:47, 11.62s/it]

Regridded data for 2014 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2014_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:09<00:00, 885.59it/s]
37it [06:57, 11.29s/it]

Regridded data for 2015 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2015_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:11<00:00, 797.49it/s]
38it [07:09, 11.39s/it]

Regridded data for 2016 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2016_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 847.06it/s]
39it [07:20, 11.27s/it]

Regridded data for 2017 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2017_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:09<00:00, 888.87it/s]
40it [07:30, 11.03s/it]

Regridded data for 2018 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2018_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:09<00:00, 889.80it/s]
41it [07:41, 10.88s/it]

Regridded data for 2019 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2019_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8784/8784 [00:09<00:00, 889.81it/s]
42it [07:51, 10.76s/it]

Regridded data for 2020 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2020_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 855.33it/s]
43it [08:02, 10.80s/it]

Regridded data for 2021 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2021_regrid_filter_850.nc



100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:10<00:00, 846.66it/s]
44it [08:13, 11.22s/it]

Regridded data for 2022 saved as F:\JuPyterNotebook\irp_ww721_bakcup\data\processed_data\ERA5_DATA\GB_ERA5_DATA\era5_pressure_level_2022_regrid_filter_850.nc


## Test Process

In [40]:
ds = xr.open_dataset(merge_era5_list[0])

In [41]:
ds = cutoff_ds(merge_era5_list[0], 50, 58, -6, 2)
ds_out = regrid(ds, ddeg_out_lat, ddeg_out_lon)

In [42]:
ds_out

<xarray.Dataset>
Dimensions:  (time: 8760, lat: 32, lon: 64)
Coordinates:
  * time     (time) datetime64[ns] 1979-01-01 ... 1979-12-31T23:00:00
  * lat      (lat) float64 50.0 50.25 50.5 50.75 51.0 ... 57.0 57.25 57.5 57.75
  * lon      (lon) float64 -6.0 -5.875 -5.75 -5.625 ... 1.5 1.625 1.75 1.875
Data variables:
    t        (time, lat, lon) float32 261.7 0.0 261.5 0.0 ... 264.2 264.2 264.3
Attributes:
    regrid_method:  bilinear
    Conventions:    CF-1.6
    history:        2023-08-26 11:48:45 GMT by grib_to_netcdf-2.25.1: /opt/ec...

In [43]:
ds_out = ds_out.where((ds_out != 0) & ~np.isnan(ds_out), drop=True)

In [44]:
ds_array = np.asarray(ds_out['t'])

In [45]:
ds_array

array([[[261.73975,       nan, 261.54614, ...,       nan, 260.09912,
               nan],
        [261.7046 , 261.5629 , 261.42117, ..., 259.8187 , 259.87036,
         259.846  ],
        [261.7162 , 261.5668 , 261.41742, ..., 259.6002 , 259.62454,
         259.5913 ],
        ...,
        [261.46216, 261.42407, 261.38602, ..., 256.72403, 256.6516 ,
         256.5813 ],
        [261.79437, 261.66544, 261.5366 , ..., 256.6801 , 256.59903,
         256.52374],
        [262.21606, 262.0862 , 261.95657, ..., 256.4985 , 256.44095,
         256.38907]],

       [[261.59326,       nan, 261.3529 , ...,       nan, 259.56784,
               nan],
        [261.50928, 261.3765 , 261.24365, ..., 259.3987 , 259.39575,
         259.3743 ],
        [261.43893, 261.31006, 261.18115, ..., 259.36264, 259.32166,
         259.27866],
        ...,
        [261.84695, 261.7033 , 261.5598 , ..., 256.76602, 256.68506,
         256.646  ],
        [262.0327 , 261.89386, 261.75513, ..., 256.7269 , 256.62054,
   

In [46]:
filled_array=fill_nan(ds_array)

100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:09<00:00, 918.78it/s]


In [47]:
nan_indices_Z = np.where(np.isnan(filled_array))
print("NaN indices in x_train:")
print(nan_indices_Z)

NaN indices in x_train:
(array([6610, 6610, 6610, 6780, 6780, 6780, 6780, 6780, 6827, 6827, 6827,
       6827, 6827, 6848, 6848, 6848, 7950, 7950, 7950, 7950, 7950, 8166,
       8166, 8166], dtype=int64), array([18, 19, 19,  7,  8,  8,  8,  8, 13, 14, 14, 14, 14,  4,  5,  5, 25,
       26, 26, 26, 26,  1,  2,  2], dtype=int64), array([0, 0, 1, 0, 0, 1, 2, 3, 0, 0, 1, 2, 3, 0, 0, 1, 0, 0, 1, 2, 3, 0,
       0, 1], dtype=int64))


In [48]:
filled_array2=fill_nan_new(ds_array)

100%|█████████████████████████████████████████████████████████████████████████████| 8760/8760 [00:09<00:00, 956.42it/s]


In [50]:
nan_indices_Z = np.where(np.isnan(filled_array2))
print("NaN indices in x_train:")
print(nan_indices_Z)

NaN indices in x_train:
(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))


In [49]:
filled_array2

array([[[261.73975, 261.64294, 261.54614, ..., 260.0619 , 260.09912,
         260.09912],
        [261.7046 , 261.5629 , 261.42117, ..., 259.8187 , 259.87036,
         259.87036],
        [261.7162 , 261.5668 , 261.41742, ..., 259.6002 , 259.62454,
         259.62454],
        ...,
        [261.46216, 261.42407, 261.38602, ..., 256.72403, 256.6516 ,
         256.6516 ],
        [261.79437, 261.66544, 261.5366 , ..., 256.6801 , 256.59903,
         256.59903],
        [262.21606, 262.0862 , 261.95657, ..., 256.4985 , 256.44095,
         256.44095]],

       [[261.59326, 261.47308, 261.3529 , ..., 259.57553, 259.56784,
         259.56784],
        [261.50928, 261.3765 , 261.24365, ..., 259.3987 , 259.39575,
         259.39575],
        [261.43893, 261.31006, 261.18115, ..., 259.36264, 259.32166,
         259.32166],
        ...,
        [261.84695, 261.7033 , 261.5598 , ..., 256.76602, 256.68506,
         256.68506],
        [262.0327 , 261.89386, 261.75513, ..., 256.7269 , 256.62054,
   

In [43]:
filled_array

array([[[261.73975, 261.64294, 261.54614, ..., 260.0619 , 260.09912,
         260.09912],
        [261.7046 , 261.5629 , 261.42117, ..., 259.8187 , 259.87036,
         259.87036],
        [261.7162 , 261.5668 , 261.41742, ..., 259.6002 , 259.62454,
         259.62454],
        ...,
        [261.46216, 261.42407, 261.38602, ..., 256.72403, 256.6516 ,
         256.6516 ],
        [261.79437, 261.66544, 261.5366 , ..., 256.6801 , 256.59903,
         256.59903],
        [262.21606, 262.0862 , 261.95657, ..., 256.4985 , 256.44095,
         256.44095]],

       [[261.59326, 261.47308, 261.3529 , ..., 259.57553, 259.56784,
         259.56784],
        [261.50928, 261.3765 , 261.24365, ..., 259.3987 , 259.39575,
         259.39575],
        [261.43893, 261.31006, 261.18115, ..., 259.36264, 259.32166,
         259.32166],
        ...,
        [261.84695, 261.7033 , 261.5598 , ..., 256.76602, 256.68506,
         256.68506],
        [262.0327 , 261.89386, 261.75513, ..., 256.7269 , 256.62054,
   

In [44]:
ds_out['t'] = xr.DataArray(filled_array, dims=ds_out['t'].dims, coords=ds_out['t'].coords)

In [45]:
ds_out

<xarray.Dataset>
Dimensions:  (time: 8760, lat: 32, lon: 64)
Coordinates:
  * time     (time) datetime64[ns] 1979-01-01 ... 1979-12-31T23:00:00
  * lat      (lat) float64 50.0 50.25 50.5 50.75 51.0 ... 57.0 57.25 57.5 57.75
  * lon      (lon) float64 -6.0 -5.875 -5.75 -5.625 ... 1.5 1.625 1.75 1.875
Data variables:
    t        (time, lat, lon) float32 261.7 261.6 261.5 ... 264.2 264.2 264.2
Attributes:
    regrid_method:  bilinear
    Conventions:    CF-1.6
    history:        2023-08-26 11:48:45 GMT by grib_to_netcdf-2.25.1: /opt/ec...