In [1]:
# Basic setting for Jupyter_notebook to import utils
import os
import sys

notebook_path = os.path.abspath("")
project_root = os.path.abspath(os.path.join(notebook_path, "../../"))

sys.path.append(project_root)

# 2 ERA5_DATA_PROCESSING

In [2]:
import os
import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from utils import folder_utils
from tqdm import tqdm

In [3]:
# Example usage

country = "GB"
data_folder = "data"
data_test_category = "test_data"
data_read_category = "raw_data"
data_save_category = "processed_data"
# output_folder = "ASOS_DATA"
output_folder2 ="ERA5_DATA"

In [4]:
folder_utils.create_folder( country, data_folder, data_test_category, output_folder2)

Folder '/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/test_data/ERA5_DATA/GB_ERA5_DATA' created successfully.


'/Users/ww721/JupyterNotebookPath/IRP_20220602/irp_ww721_bakcup/data/test_data/ERA5_DATA/GB_ERA5_DATA'

In [5]:
def extract_data_nc_to_xr(country, data_folder, data_category, output_folder):
    # Specify the folder path
    input_folder_path = folder_utils.find_folder(
        country, data_folder, data_category, output_folder
    )
    raw_ds = None  # Initialize raw_ds outside the loop
    nc_files = [
        f
        for f in os.listdir(input_folder_path)
        if f.endswith('.nc') and "era5_station_network" not in f
    ]
    # Read and merge the csv files in queue
    for nc_file in tqdm(nc_files):
        nc_file_path = os.path.join(input_folder_path, nc_file)
        raw_ds = xr.open_dataset(nc_file_path)
        # raw_df = pd.concat([raw_df, df], ignore_index=True)

    return raw_ds


In [6]:
ds = extract_data_nc_to_xr(country, data_folder, data_test_category, output_folder2)

100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.38it/s]


In [7]:
print(ds)

<xarray.Dataset>
Dimensions:    (longitude: 41, latitude: 45, time: 744)
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2023-01-01 ... 2023-01-31T23:00:00
Data variables:
    u10        (time, latitude, longitude) float32 ...
    v10        (time, latitude, longitude) float32 ...
    d2m        (time, latitude, longitude) float32 ...
    t2m        (time, latitude, longitude) float32 ...
    i10fg      (time, latitude, longitude) float32 ...
    msl        (time, latitude, longitude) float32 ...
    skt        (time, latitude, longitude) float32 ...
    sp         (time, latitude, longitude) float32 ...
    tp         (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-08-14 13:08:35 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...


In [8]:
ds.dims

Frozen({'longitude': 41, 'latitude': 45, 'time': 744})

In [9]:
ds.data_vars

Data variables:
    u10      (time, latitude, longitude) float32 ...
    v10      (time, latitude, longitude) float32 ...
    d2m      (time, latitude, longitude) float32 ...
    t2m      (time, latitude, longitude) float32 ...
    i10fg    (time, latitude, longitude) float32 ...
    msl      (time, latitude, longitude) float32 ...
    skt      (time, latitude, longitude) float32 ...
    sp       (time, latitude, longitude) float32 ...
    tp       (time, latitude, longitude) float32 ...

In [10]:
ds.coords

Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2023-01-01 ... 2023-01-31T23:00:00

In [11]:
ds.attrs

{'Conventions': 'CF-1.6',
 'history': '2023-08-14 13:08:35 GMT by grib_to_netcdf-2.25.1: /opt/ecmwf/mars-client/bin/grib_to_netcdf.bin -S param -o /cache/data9/adaptor.mars.internal-1692018500.2390654-25204-1-38ad28e7-7189-4dcf-abc4-d4ef8d4cf8e3.nc /cache/tmp/38ad28e7-7189-4dcf-abc4-d4ef8d4cf8e3-adaptor.mars.internal-1692018168.885484-25204-1-tmp.grib'}

In [12]:
ds.longitude

<xarray.DataArray 'longitude' (longitude: 41)>
array([-8.  , -7.75, -7.5 , -7.25, -7.  , -6.75, -6.5 , -6.25, -6.  , -5.75,
       -5.5 , -5.25, -5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25,
       -3.  , -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,
        2.  ], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
Attributes:
    units:      degrees_east
    long_name:  longitude

In [13]:
ds.latitude

<xarray.DataArray 'latitude' (latitude: 45)>
array([61.  , 60.75, 60.5 , 60.25, 60.  , 59.75, 59.5 , 59.25, 59.  , 58.75,
       58.5 , 58.25, 58.  , 57.75, 57.5 , 57.25, 57.  , 56.75, 56.5 , 56.25,
       56.  , 55.75, 55.5 , 55.25, 55.  , 54.75, 54.5 , 54.25, 54.  , 53.75,
       53.5 , 53.25, 53.  , 52.75, 52.5 , 52.25, 52.  , 51.75, 51.5 , 51.25,
       51.  , 50.75, 50.5 , 50.25, 50.  ], dtype=float32)
Coordinates:
  * latitude  (latitude) float32 61.0 60.75 60.5 60.25 ... 50.75 50.5 50.25 50.0
Attributes:
    units:      degrees_north
    long_name:  latitude

In [14]:
ds.time

<xarray.DataArray 'time' (time: 744)>
array(['2023-01-01T00:00:00.000000000', '2023-01-01T01:00:00.000000000',
       '2023-01-01T02:00:00.000000000', ..., '2023-01-31T21:00:00.000000000',
       '2023-01-31T22:00:00.000000000', '2023-01-31T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2023-01-01 ... 2023-01-31T23:00:00
Attributes:
    long_name:  time

In [15]:
ds.d2m.attrs

{'units': 'K', 'long_name': '2 metre dewpoint temperature'}

In [16]:
ds.d2m.long_name

'2 metre dewpoint temperature'

In [17]:
ds.longitude.shape

(41,)

In [18]:
ds.latitude.shape[0]

45

In [19]:
ds.latitude.shape

(45,)

In [20]:
ds.latitude.values[0]

61.0

In [21]:
ds.d2m.shape

(744, 45, 41)

In [22]:
print('Latitudes and longitudes of domain corners:')
pt1 = 0
pt2 = 0
print('  0, 0:        ', ds.latitude.values[pt1], ds.longitude.values[pt2])
pt1 = ds.latitude.shape[0] - 1
print('  0, x-max:    ', ds.latitude.values[pt1], ds.longitude.values[pt2])
pt = ds.latitude.shape[0] - 1
print('  y-max, 0:    ', ds.latitude.values[pt], ds.longitude.values[pt])
pt = ds.latitude.shape[0] - 1
pt2 = ds.longitude.shape[0] - 1
print('  y-max, x-max:', ds.latitude.values[pt], ds.longitude.values[pt2])

Latitudes and longitudes of domain corners:
  0, 0:         61.0 -8.0
  0, x-max:     50.0 -8.0


IndexError: index 44 is out of bounds for axis 0 with size 41

In [23]:
ds.latitude.values # 提取数值

array([61.  , 60.75, 60.5 , 60.25, 60.  , 59.75, 59.5 , 59.25, 59.  ,
       58.75, 58.5 , 58.25, 58.  , 57.75, 57.5 , 57.25, 57.  , 56.75,
       56.5 , 56.25, 56.  , 55.75, 55.5 , 55.25, 55.  , 54.75, 54.5 ,
       54.25, 54.  , 53.75, 53.5 , 53.25, 53.  , 52.75, 52.5 , 52.25,
       52.  , 51.75, 51.5 , 51.25, 51.  , 50.75, 50.5 , 50.25, 50.  ],
      dtype=float32)

In [24]:
ds.latitude.values[3:5]   # like numpy

array([60.25, 60.  ], dtype=float32)

In [25]:
# Data Description
for i in ds.data_vars:
    print("--------------------------------------------------------------------")
    print(i)
    print("--------------------------------------------------------------------")
    var_data = ds[i]
    print(var_data)

--------------------------------------------------------------------
u10
--------------------------------------------------------------------
<xarray.DataArray 'u10' (time: 744, latitude: 45, longitude: 41)>
[1372680 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) datetime64[ns] 2023-01-01 ... 2023-01-31T23:00:00
Attributes:
    units:      m s**-1
    long_name:  10 metre U wind component
--------------------------------------------------------------------
v10
--------------------------------------------------------------------
<xarray.DataArray 'v10' (time: 744, latitude: 45, longitude: 41)>
[1372680 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -8.0 -7.75 -7.5 -7.25 ... 1.25 1.5 1.75 2.0
  * latitude   (latitude) float32 61.0 60.75 60.5 60.25 ... 50.5 50.25 50.0
  * time       (time) date

In [26]:
# data values
for i in ds.data_vars:
    print(var_data.values)

[[[1.90222636e-06 9.51113179e-07 4.75673005e-07 ... 7.13369809e-06
   1.09383836e-05 2.81543471e-05]
  [1.90222636e-06 9.51113179e-07 4.75673005e-07 ... 1.42678618e-06
   8.08481127e-06 2.67275609e-05]
  [1.42678618e-06 9.51113179e-07 4.75673005e-07 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  ...
  [3.09982104e-04 2.92766141e-04 1.55894551e-04 ... 7.29537569e-05
   5.09819947e-05 4.95552085e-05]
  [3.01802065e-04 2.88961455e-04 2.06496101e-04 ... 2.57764477e-05
   8.08481127e-06 7.13369809e-06]
  [1.79293100e-04 1.66452490e-04 1.53992325e-04 ... 1.90222636e-06
   3.00565735e-05 8.48432537e-05]]

 [[6.77222852e-05 2.72030011e-05 9.51113179e-07 ... 0.00000000e+00
   0.00000000e+00 4.75673005e-07]
  [9.51159745e-06 9.51113179e-07 9.51113179e-07 ... 0.00000000e+00
   0.00000000e+00 4.75673005e-07]
  [1.90222636e-06 4.75673005e-07 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  ...
  [3.07604205e-04 3.20920255e-04 2.67465366e-04 ... 3.50501155e-04
   2.41308